# File: configs/config_adc.yaml
# Configuration for training ADC on the IROS2020 N=10 dataset format

# Experiment Name / Output Directory (within results/)
exp_name: 'adc_k10_N10_P6_IROS_Data' # Updated Name

# --- Model Architecture ---
# CNN (Input: FOV)
channels: [16, 16, 16]      # Output channels of CNN layers. Input is 3 channels.
strides: [1, 1, 1]           # Stride for each CNN layer.
kernels: [3, 3, 3]           # Kernel size for each CNN layer.
paddings: [1, 1, 1]          # Padding for Conv2d layers (internal to CNN).

# Encoder MLP (after CNN flatten)
encoder_layers: 1
encoder_dims: [64]

# GNN - ADC Specific Settings
net_type: 'gnn'
msg_type: 'adc'
graph_filters: [10]          # Truncation order K for ADC layer(s).
node_dims: [128]             # Output dimension of ADC layer(s).
# Optional ADC Layer parameters (using defaults in ADCLayer if omitted):
# adc_initial_t: 1.0
# adc_train_t: True

# Policy MLP (after GNN/ADC)
action_layers: 1

# --- Training Hyperparameters ---
epochs: 50                   # Adjust as needed, ADC might need more than GCN
learning_rate: 3e-4
weight_decay: 1e-4
batch_size: 128              # Adjust based on GPU memory
num_workers: 0               # Start with 0 for debugging data loading
eval_frequency: 5

# --- Online Expert (DAgger) ---
# OE is DISABLED in train.py when using MatDataset. This section is ignored.
# online_expert:
#   frequency_epochs: 4
#   num_cases_to_run: 500
#   cbs_timeout_seconds: 15

# --- Evaluation ---
tests_episodes: 50           # Number of random episodes per evaluation phase
eval_board_size: [20, 20]    # Use same board size as training data for eval
eval_obstacles: 40           # Use similar obstacle count as training data (~10%)
eval_max_steps: 500        # Optional override, defaults to max_steps

# --- Environment & Simulation Parameters ---
# !!! THESE MUST MATCH THE DATA IN THE .MAT FILES !!!
num_agents: 10               # <<<--- CORRECTED based on .mat data
pad: 6                       # <<<--- CORRECTED based on .mat FOV shape (11x11)
map_shape: [11, 11]          # <<<--- CORRECTED derived from pad=6

# Parameters matching environment context of .mat data
board_size: [20, 20]         # <<<--- CORRECTED based on .mat map shape
sensing_range: 5             # <<<--- ASSUMED based on paper (r_comm=5)
max_time: 500                # Max sim time for eval env (adjust as needed)
max_steps: 500               # Alias for max_time

# --- Data Loading ---
# !!! POINT THESE TO YOUR .MAT FILE DIRECTORIES !!!
train:
    root_dir: 'dataset/IROS_N10_P6_Converted/train' # <<<--- VERIFY PATH
    # Other keys like mode, min/max_time, nb_agents are ignored by MatDataLoader

valid:
    root_dir: 'dataset/IROS_N10_P6_Converted/valid' # <<<--- VERIFY PATH
    # Other keys like mode, min/max_time, nb_agents are ignored by MatDataLoader

# test: # Optional: configure test set path if needed later
#    root_dir: '/path/to/your/mat/test/folder'