# File: configs/config_train_mat.yaml
# Example config for training using the .mat dataset format

# Experiment Name / Output Directory (within results/)
exp_name: 'gnn_train_on_mat_N10_P6' # <<< CHANGE NAME (N10=Agents, P6=Pad if FOV 11x11)

# --- Model Architecture ---
# !!! Ensure these match the model you want to train !!!
net_type: 'gnn'      # 'gnn' or 'baseline'
msg_type: 'gcn'      # GNN type if net_type='gnn' (e.g., 'gcn', 'adc')

channels: [16, 16, 16]
strides: [1, 1, 1]
kernels: [3, 3, 3]
paddings: [1, 1, 1] # Padding for Conv layers, NOT the FOV pad

encoder_layers: 1
encoder_dims: [64]

# --- GNN Specific (ignored if net_type='baseline') ---
# Example for GCN K=3
graph_filters: [3]
node_dims: [128]
# Example for ADC K=10
# graph_filters: [10]
# node_dims: [128]
# initial_t: 1.0 # Optional for ADC
# train_t: True # Optional for ADC

action_layers: 1
# action_hidden_dims: [] # Only needed if action_layers > 1

# --- Training Hyperparameters ---
epochs: 50                # Number of training epochs
learning_rate: 3e-4       # Adam learning rate
weight_decay: 1e-4        # Adam weight decay
batch_size: 128           # Number of samples (timesteps) per batch
num_workers: 0            # DataLoader workers (0 for debug, increase later)
eval_frequency: 5         # Evaluate model performance every N epochs

# --- Evaluation ---
# Parameters for evaluation runs performed *during* training
tests_episodes: 50        # Number of random episodes per evaluation phase
# eval_max_steps: 120     # Optional override (defaults to max_steps)
# These should generally match the *training* data config unless testing generalization
eval_board_size: [20, 20]
eval_obstacles: 40
# eval_num_agents: 10     # Will use num_agents_config from above
# eval_sensing_range: 5
# eval_pad: 6             # Will use pad_config from above

# --- Environment & Simulation Parameters ---
# !!! THESE MUST MATCH THE DATA IN THE .MAT FILES !!!
num_agents: 10            # <<<--- MATCH .mat DATA 'N' (e.g., 10)
pad: 6                    # <<<--- MATCH .mat DATA 'H'/'W' (e.g., pad=6 for 11x11)
map_shape: [11, 11]       # <<<--- MUST BE [2*pad-1, 2*pad-1]

# These are less critical for loading but define the eval env behavior
board_size: [20, 20]      # Board size the agents *operated in* for the dataset
sensing_range: 5          # Communication range used for GSO in dataset
max_time: 150             # Max sim time for eval env (used for truncation)
max_steps: 150            # Alias for max_time if eval_max_steps not set

# --- Data Loading ---
# !!! POINT THESE TO YOUR .MAT FILE DIRECTORIES !!!
train:
    root_dir: 'dataset/DataSource_DMap_FixedComR/EffectiveDensity/Training/map20x20_density_p1/10_Agent/train' # <<<--- UPDATE PATH
    # 'mode', 'min_time', 'max_time_dl', 'nb_agents' keys are ignored by MatDataLoader

valid:
    root_dir: 'dataset/DataSource_DMap_FixedComR/EffectiveDensity/Training/map20x20_density_p1/10_Agent/valid' # <<<--- UPDATE PATH
    # 'mode', 'min_time', 'max_time_dl', 'nb_agents' keys are ignored by MatDataLoader

# test: # Optional: configure test set path if needed later
#    root_dir: '/path/to/your/mat/test/folder'